### ISSUE TITLE
Metronome keeps resetting to 0 at certain attacks and such. Not sure what's causing it but it makes the metronome unusable.

### ISSUE THREAD

**Issue by Mdthompson900** [vincent0955/Visual-metronome#19] opened 2022-10-21 08:06 UTC

**Comment by vincent0955** [comment] 2022-10-23 08:02
I've heard this issue from some other person but as of right now, I have no idea what could be causing this bug. there's nothing in the code that looks like it causes it, I haven't updated the plugin in a while, and it seems to be a new issue too. So sorry, I'll maybe try to fix it in the future.

**Comment by Mdthompson900** [comment] 2022-10-24 01:36
From what I can tell, certain actions reset it. You pick from a calquat and it'll turn it to 0. Some melee actions also reset it as well. 

Is there any sort of investigation or help I can do to help with this? It only seems to have started within the last month or two.

**Comment by vincent0955** [comment] 2022-10-28 07:02
feel free to investigate the issue yourself if you want. Ill be grateful if you find out a way to fix it. I haven't played in a while so I don't have any way of getting any other knowledge about this issue

**Comment by MarkoMiljusevic** [comment] 2022-11-23 22:52
Just wanted to add I also get this issue when attacking with a scythe as well I've noticed it resetting every 5 ticks quite often even if I have it set to more than 5

**Comment by vincent0955** [comment] 2022-11-25 01:22
Yeah I've gotten more reports from a quite few people now about this issue, mostly in ToB where it just resets randomly. My only idea right now is either another plugin is interfering with it (idk how that would work), but maybe its just something in runelite or in osrs that is causing this, since it seem to start happening around the release of toa.

So if anyone else is having this issue and sees this in the future, if you want to help you can try to find the cause by disabling plugins and seeing if it affects it. But other than that unfortunately I still don't know the cause of this issue.

**Comment by WhatTheHai** [comment] 2023-01-20 13:47
Got the bug too and was testing around for a bit. Seems to be specifically caused by the Weapon Charges plugin with the (Sanguine) Scythe of Vitur. I tried testing it out on a combat dummy and it seems to be resetting on that specific item. Trying other items which the plugin supports doesn't seem to reset the metronome (Tumeken's Shadow and Blowpipe)

**Comment by rasheedja** [comment] 2023-02-07 19:32
Thanks, @WhatTheHai.

The issue seems to be caused when Weapon Charges is enabled and using a charged weapon. My tick counter was resetting when I was fighting muspah with a trident. Disabling Weapon Charges resolved the issue.

**Comment by Thource** [comment] 2023-03-08 12:15
Disabling other plugins is not the solution for this issue. This issue happens because this plugin doesn't check what actually changed in the `onConfigChanged` function.

You need to apply something similar to the fix that I applied for the MonsterHP plugin, see here: https://github.com/lejeffe/MonsterHP/commit/faf4a88c2934a5bb1ed9597ebb2858abf49c72dd

**Comment by vincent0955** [comment] 2023-03-08 18:26
Wouldn't the check I currently have suffice for this problem though? This is the onConfigChanged function right now:
```
public void onConfigChanged(ConfigChanged event)
    {
        if (tickCounter > config.colorCycle())
        {
            tickCounter = 0;
        }
        DEFAULT_SIZE = new Dimension(config.boxWidth(), config.boxWidth());
    }
```

The counter should only reset when the config is changed AND the tickCounter is above what it should be. So I don't see why it would reset when onConfigChanged is triggered but tickCounter is still below what colorCycle is set to?

**Comment by Thource** [comment] 2023-03-08 19:48
I've found the real issue, you have 2 variables in this plugin and swap between them depending on the amount of ticks between colour changes. If you set `tickCount` to a value higher than `colorCycle`, your plugin resets the tick counter on every config change.

I'll fix this and submit a PR

**Comment by Thource** [comment] 2023-03-08 20:13
Fixed by https://github.com/vincent0955/Visual-metronome/pull/26

**Comment by vincent0955** [comment] 2023-03-09 00:36
ohhh, yes that is exactly the problem, I don't know how I didn't notice that before. I'll test out the pull request and merge it. Thanks for helping out.

**Comment by vincent0955** [comment] 2023-03-17 17:50
Should be fixed now after recent update.

**Closed as completed by vincent0955** 2023-03-17 17:50 UTC
